version: '3'

services:
  docker-mysql:
    image: mysql:5.7.32
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_PASSWORD=root
    ports:
      - 3306:3306
    command: --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql
