SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
SET NAMES 'utf8mb4';

CREATE DATABASE IF NOT EXISTS test;

USE test;

DROP TABLE IF EXISTS `test`.`SHOP`;

CREATE TABLE `test`.`SHOP` (
  `id` MEDIUMINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(10) NOT NULL,
  `version` INT NOT NULL,
  PRIMARY KEY (`id`)
);

DROP TABLE IF EXISTS `test`.`PRODUCT`;

CREATE TABLE `test`.`PRODUCT` (
  `id` MEDIUMINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(10) NOT NULL,
  `shop_id` MEDIUMINT NOT NULL,
  `version` INT NOT NULL,
  CONSTRAINT `shop_id_fk`
      FOREIGN KEY (`shop_id`)
      REFERENCES `SHOP` (`id`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  PRIMARY KEY (`id`)
);
